spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  sql:
    init:
      mode: never
logging:
  level:
    org:
      hibernate:
        SQL: error
        type: error
    com:
      ivory.ivory: info
swagger:
  server:
    url: https://ivorygroup.click