spring:
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB
  profiles:
    active: local
  application:
    name: Ivory
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
cloud:
  aws:
    s3:
      bucket: goormthon-bucket
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

ocr:
    api:
        secret-key: ${OCR_API_SECRET}
        url: ${OCR_API_URL}
    medical-certificate:
        api:
            secret-key: ${MEDICAL_CERTIFICATE_OCR_API_SECRET_KEY}
            url: ${MEDICAL_CERTIFICATE_OCR_API_URL}
kakaopay:
    secretKey: ${KAKAOPAY_SECRET_KEY}
    cid: ${CID}

jwt:
  secret: ${JWT_SECRET}